name: Build and push image to ECR

on:
  release:
    types: [published]
  push:
    tags: ['*']
    # branches: [master]
    # branches: [release]
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string

env:
  APPLICATION_NAME: "flashgpt-backend-service"

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.APPLICATION_NAME }}:${{ github.sha }} -t $ECR_REGISTRY/${{ env.APPLICATION_NAME }}:latest .
          docker push $ECR_REGISTRY/${{ env.APPLICATION_NAME }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.APPLICATION_NAME }}:latest